version: '3.9'

services:
  app:
    #build: ./app
    image: medtracker:latest
    container_name: med_tracker_app
    pull_policy: always
    restart: unless-stopped
    expose:
      - "5000"
    environment:
      - FLASK_ENV=production
    depends_on:
      db:
        condition: service_healthy  

  nginx:
    image: nginx:alpine
    container_name: med_tracker_nginx
    ports:
      - "5080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app/static:/app/static:ro
    depends_on:
      - app
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: med_tracker_db
    environment:
      POSTGRES_USER: meduser
      POSTGRES_PASSWORD: medpass
      POSTGRES_DB: medtracker
    volumes:
      - med_tracker_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U meduser -d medtracker"]
      interval: 5s
      timeout: 5s
      retries: 5  

volumes:
  med_tracker_db_data: